// ============================================================
// Kwality Book Centre — Books Data
// Real titles, authors, ISBNs carried in the store
// ============================================================

const BOOKS = [
  // ── UPSC / Civil Services ──
  {
    id: 1,
    title: "Indian Polity",
    author: "M. Laxmikanth",
    edition: "7th Edition, 2025",
    publisher: "McGraw Hill Education",
    price: 695,
    mrp: 750,
    category: "upsc",
    badge: "Bestseller",
    badgeType: "hot",
    gradient: ["#0f3460","#16213e","#1a1a2e"],
    textColor: "#60a5fa",
    description: "The undisputed bible for UPSC Polity. Covers all aspects of Indian Constitution, political system, governance.",
    inStock: true,
    rating: 4.9,
    reviews: 2847
  },
  {
    id: 2,
    title: "Spectrum — A Brief History of Modern India",
    author: "Rajiv Ahir",
    edition: "2025 Edition",
    publisher: "Spectrum Books",
    price: 420,
    mrp: 450,
    category: "upsc",
    badge: "Must Read",
    badgeType: "info",
    gradient: ["#1a472a","#2d6a4f","#40916c"],
    textColor: "#a7f3d0",
    description: "Comprehensive modern Indian history from 1757 to independence. Essential for UPSC Prelims & Mains.",
    inStock: true,
    rating: 4.7,
    reviews: 1923
  },
  {
    id: 3,
    title: "Indian Economy — Key Concepts",
    author: "Ramesh Singh",
    edition: "14th Edition 2025",
    publisher: "McGraw Hill",
    price: 520,
    mrp: 560,
    category: "upsc",
    badge: "New Edition",
    badgeType: "new",
    gradient: ["#7c2d12","#c2410c","#ea580c"],
    textColor: "#fed7aa",
    description: "Most comprehensive book for UPSC economy section. Updated with Budget 2025 analysis.",
    inStock: true,
    rating: 4.6,
    reviews: 1456
  },
  {
    id: 4,
    title: "Certificate Physical & Human Geography",
    author: "G.C. Leong",
    edition: "Revised Edition",
    publisher: "Oxford University Press",
    price: 345,
    mrp: 375,
    category: "upsc",
    badge: null,
    badgeType: null,
    gradient: ["#164e63","#0e7490","#0891b2"],
    textColor: "#a5f3fc",
    description: "The standard geography reference for UPSC aspirants. Clear maps, diagrams & explanations.",
    inStock: true,
    rating: 4.5,
    reviews: 987
  },
  {
    id: 5,
    title: "Ethics, Integrity & Aptitude",
    author: "G. Subba Rao & P.N. Roy Chowdhury",
    edition: "9th Edition 2025",
    publisher: "McGraw Hill",
    price: 480,
    mrp: 510,
    category: "upsc",
    badge: "GS Paper 4",
    badgeType: "info",
    gradient: ["#4c1d95","#6d28d9","#7c3aed"],
    textColor: "#ddd6fe",
    description: "Comprehensive coverage of UPSC GS Paper 4 Ethics. Case studies, practice questions & model answers.",
    inStock: true,
    rating: 4.8,
    reviews: 1123
  },

  // ── SSC / Banking ──
  {
    id: 6,
    title: "Lucent's General Knowledge 2025",
    author: "Lucent Editorial Board",
    edition: "2025 Updated",
    publisher: "Lucent Publications",
    price: 285,
    mrp: 300,
    category: "ssc",
    badge: "All-Time Classic",
    badgeType: "hot",
    gradient: ["#0c4a6e","#075985","#0284c7"],
    textColor: "#bae6fd",
    description: "India's most popular GK book. Complete coverage of static GK for all competitive exams.",
    inStock: true,
    rating: 4.8,
    reviews: 5234
  },
  {
    id: 7,
    title: "Quantitative Aptitude for CAT",
    author: "Arun Sharma",
    edition: "9th Edition",
    publisher: "McGraw Hill",
    price: 595,
    mrp: 640,
    category: "ssc",
    badge: "CAT / SSC",
    badgeType: "info",
    gradient: ["#065f46","#047857","#059669"],
    textColor: "#a7f3d0",
    description: "The definitive aptitude book for MBA & SSC exams. Concepts + 4000+ practice questions.",
    inStock: true,
    rating: 4.7,
    reviews: 2341
  },
  {
    id: 8,
    title: "Plinth to Paramount — English Grammar",
    author: "Neetu Singh",
    edition: "Vol 1 & 2",
    publisher: "KD Campus",
    price: 480,
    mrp: 520,
    category: "ssc",
    badge: "SSC Standard",
    badgeType: "hot",
    gradient: ["#831843","#9d174d","#be185d"],
    textColor: "#fbcfe8",
    description: "The go-to English grammar guide for SSC CGL, CHSL, and other government exams.",
    inStock: true,
    rating: 4.6,
    reviews: 1876
  },
  {
    id: 9,
    title: "Kiran SSC Mathematics 1999–2025",
    author: "Kiran Editorial Board",
    edition: "Chapter-wise, 2025",
    publisher: "Kiran Prakashan",
    price: 450,
    mrp: 490,
    category: "ssc",
    badge: "Previous Papers",
    badgeType: "new",
    gradient: ["#312e81","#3730a3","#4338ca"],
    textColor: "#c7d2fe",
    description: "25 years of SSC Maths solved papers, chapter-wise with detailed solutions.",
    inStock: true,
    rating: 4.5,
    reviews: 1543
  },

  // ── School Books ──
  {
    id: 10,
    title: "NCERT Physics Part I",
    author: "NCERT",
    edition: "Class 12, 2024–25",
    publisher: "NCERT (Official)",
    price: 110,
    mrp: 110,
    category: "school",
    badge: "NCERT Official",
    badgeType: "info",
    gradient: ["#1e3a8a","#1d4ed8","#2563eb"],
    textColor: "#bfdbfe",
    description: "Official NCERT Class 12 Physics textbook. Essential for board exams and JEE foundation.",
    inStock: true,
    rating: 4.9,
    reviews: 8761
  },
  {
    id: 11,
    title: "Mathematics for Class 12",
    author: "R.D. Sharma",
    edition: "2025 Edition (Vol 1 & 2)",
    publisher: "Dhanpat Rai Publications",
    price: 890,
    mrp: 950,
    category: "school",
    badge: "Students' Choice",
    badgeType: "hot",
    gradient: ["#6b21a8","#7c3aed","#8b5cf6"],
    textColor: "#ede9fe",
    description: "Comprehensive Class 12 maths with 20,000+ solved examples. The reference book for serious students.",
    inStock: true,
    rating: 4.8,
    reviews: 4328
  },
  {
    id: 12,
    title: "Concepts of Physics (Vol 1 + 2)",
    author: "H.C. Verma",
    edition: "Revised Edition",
    publisher: "Bharati Bhawan",
    price: 680,
    mrp: 720,
    category: "school",
    badge: "JEE Standard",
    badgeType: "info",
    gradient: ["#0f172a","#1e293b","#334155"],
    textColor: "#cbd5e1",
    description: "The most loved physics book in India. Used by millions of JEE aspirants. Builds concepts from scratch.",
    inStock: true,
    rating: 4.9,
    reviews: 6543
  },
  {
    id: 13,
    title: "NCERT Chemistry Class 12",
    author: "NCERT",
    edition: "Part I & Part II",
    publisher: "NCERT (Official)",
    price: 220,
    mrp: 220,
    category: "school",
    badge: "NCERT Official",
    badgeType: "info",
    gradient: ["#14532d","#166534","#15803d"],
    textColor: "#bbf7d0",
    description: "Official NCERT Chemistry for Class 12. Covers both parts — Organic, Inorganic & Physical Chemistry.",
    inStock: true,
    rating: 4.8,
    reviews: 5234
  },
  {
    id: 14,
    title: "33 Years JEE Advanced Solved Papers",
    author: "Disha Experts",
    edition: "2025 Edition",
    publisher: "Disha Publication",
    price: 585,
    mrp: 620,
    category: "school",
    badge: "JEE / NEET",
    badgeType: "new",
    gradient: ["#7c1d1d","#991b1b","#b91c1c"],
    textColor: "#fecaca",
    description: "Chapter-wise solved papers of all 33 years of JEE Advanced (1992–2024). Essential practice resource.",
    inStock: false,
    rating: 4.7,
    reviews: 1892
  },

  // ── Stationery ──
  {
    id: 15,
    title: "Classmate Four Subject Spiral",
    author: "ITC Classmate",
    edition: "300 Pages, A4 Ruled",
    publisher: "ITC Limited",
    price: 125,
    mrp: 135,
    category: "stationery",
    badge: "Value for Money",
    badgeType: "info",
    gradient: ["#7c3aed","#6d28d9","#5b21b6"],
    textColor: "#ddd6fe",
    description: "Premium 4-subject spiral notebook. 300 pages, micro-perforated, A4 size. Best for college students.",
    inStock: true,
    rating: 4.5,
    reviews: 423
  },
  {
    id: 16,
    title: "Staedtler Pencil Tin — 12 HB",
    author: "Staedtler Germany",
    edition: "Noris 120 Series",
    publisher: "Staedtler",
    price: 185,
    mrp: 200,
    category: "stationery",
    badge: "Premium Import",
    badgeType: "hot",
    gradient: ["#b45309","#d97706","#f59e0b"],
    textColor: "#1a1a1a",
    description: "World-renowned German pencils. 12 HB grade pencils in iconic yellow-black design. Smooth writing.",
    inStock: true,
    rating: 4.8,
    reviews: 276
  },
  {
    id: 17,
    title: "Pilot V7 Hi-Tecpoint Pen (Blue, 12 pcs)",
    author: "Pilot Japan",
    edition: "0.7mm Needle Point",
    publisher: "Pilot Corporation",
    price: 380,
    mrp: 420,
    category: "stationery",
    badge: "Top Pick",
    badgeType: "hot",
    gradient: ["#0e7490","#0891b2","#06b6d4"],
    textColor: "#cffafe",
    description: "The most preferred pen by UPSC aspirants & exam-takers. Clean, consistent 0.7mm line. Pack of 12.",
    inStock: true,
    rating: 4.9,
    reviews: 891
  },
  {
    id: 18,
    title: "Doms Geometry Box Deluxe",
    author: "DOMS Industries",
    edition: "15-Piece Complete Set",
    publisher: "DOMS",
    price: 145,
    mrp: 160,
    category: "stationery",
    badge: null,
    badgeType: null,
    gradient: ["#065f46","#047857","#10b981"],
    textColor: "#d1fae5",
    description: "Complete 15-piece geometry box with compass, divider, rulers, protractor, and set squares.",
    inStock: true,
    rating: 4.4,
    reviews: 312
  }
];

// Binding services data
const BINDING_TYPES = [
  { id: "spiral", name: "Spiral Binding", pricePerPage: 0.25, base: 30, minPages: 10, description: "Best for projects, reports, presentations" },
  { id: "hard",   name: "Hard Cover Binding", pricePerPage: 0.35, base: 80, minPages: 40, description: "Thesis, dissertations, official docs" },
  { id: "soft",   name: "Soft Cover Binding", pricePerPage: 0.20, base: 50, minPages: 20, description: "Paperback style, journals, notebooks" },
  { id: "staple", name: "Saddle Stitch (Staple)", pricePerPage: 0.10, base: 15, minPages: 8, description: "Booklets, pamphlets, newsletters" }
];

// Testimonials
const TESTIMONIALS = [
  {
    id: 1,
    name: "Abhishek Rana",
    role: "UPSC Aspirant",
    area: "Lodhi Colony, Delhi",
    rating: 5,
    text: "Best bookstore in South Delhi for UPSC prep! I found Laxmikanth, Spectrum, Vision IAS notes — all here. Staff guided me perfectly on which edition to buy. Honest pricing — exactly MRP.",
    avatar: "AR",
    avatarBg: "#1e3a8a"
  },
  {
    id: 2,
    name: "Priya Nair",
    role: "Engineering Student",
    area: "Lady Shri Ram College, Delhi",
    rating: 5,
    text: "Got my final year project spiral-bound here in under 30 minutes. The quality is immaculate — perfect clear cover, colour-matched back, sharp spiral. Definitely my go-to for all binding.",
    avatar: "PN",
    avatarBg: "#7c3aed"
  },
  {
    id: 3,
    name: "Rajesh Kapoor",
    role: "Parent",
    area: "Defence Colony, New Delhi",
    rating: 5,
    text: "We've bought our kids' CBSE books here every year for 8 years. Huge collection, all genuinely published books, and the staff remembers our kids by name. Extremely trustworthy.",
    avatar: "RK",
    avatarBg: "#065f46"
  },
  {
    id: 4,
    name: "Sneha Malhotra",
    role: "SSC CGL Qualifier",
    area: "Jor Bagh, New Delhi",
    rating: 5,
    text: "Lucent, Kiran, Rakesh Yadav — everything was in stock! I cleared SSC CGL this year and honestly, having all prep books available nearby saved me so much time. Thank you Kwality Book Centre!",
    avatar: "SM",
    avatarBg: "#b45309"
  },
  {
    id: 5,
    name: "Dr. Anand Krishnan",
    role: "PhD Scholar, JNU",
    area: "New Delhi",
    rating: 5,
    text: "Had my 380-page thesis bound in premium hard cover. Embossed title, maroon cover — it looks absolutely professional. The binding specialist here is incredibly skilled. Highly recommend.",
    avatar: "AK",
    avatarBg: "#831843"
  }
];
